name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: 
          ls && cd ZPET && ls && 
          g++ main.cpp misc.cpp misc.h device.cpp device.hpp moduleproc/module.cpp moduleproc/processor.cpp moduleproc/processor.hpp moduleproc/module.hpp -o ZPET
