name: ZPETv2 macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: 
          ls && cd ZPET && ls && 
          g++ main.cpp misc.cpp misc.h module.cpp processor.cpp processor.hpp module.hpp -o ZPET
